// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "border mt-24"
            }, React.createElement("h1", undefined, "About Page"));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
