// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "flex"
            }, React.createElement("div", undefined, React.createElement("h1", {
                      className: "text-3xl font-bold"
                    }, "Let's Level Up with Functional Programming")), React.createElement("div", {
                  className: "relative z-0 w-192 h-full border-solid border-2 border-blue neg-pt-1"
                }, React.createElement("img", {
                      className: "absolute z-0 neg-top-16 left-16 border-2 border-solid border-blue",
                      src: "/static/triangle-unit.svg"
                    })));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
