// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "relative flex justify-end w-full mt-16"
            }, React.createElement("div", {
                  className: "absolute top-10 sm:top-20 left-0 w-full md:w-max-80"
                }, React.createElement("h1", {
                      className: "text-xl w-40 sm:text-2xl sm:w-56 md:text-4xl md:w-66 font-bold"
                    }, "Let's Level Up with Functional Programming")), React.createElement("div", {
                  className: "relative min-w-48 w-full z-0 sm:w-172 h-full neg-pt-1"
                }, React.createElement("img", {
                      className: "absolute z-0 object-cover neg-top-16 left-8 sm:neg-top-32 sm:left-16",
                      src: "/static/triangle-unit.svg"
                    })));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
