// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "relative flex justify-end mt-8"
            }, React.createElement("div", {
                  className: "absolute left-0 w-max-80 w-80"
                }, React.createElement("h1", {
                      className: "text-5xl font-bold"
                    }, "Let's Level Up with Functional Programming")), React.createElement("div", {
                  className: "relative z-0 w-172 h-full neg-pt-1"
                }, React.createElement("img", {
                      className: "absolute z-0 neg-top-32 left-16",
                      src: "/static/triangle-unit.svg"
                    })));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
