// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "./layouts/MainLayout.mjs";
import * as Router from "next/router";

var set_body_class = (function(page_props) {
	  document.body.className = page_props.is_dark ? "dark-mode" : "light-mode"
  });

function $$default(props) {
  var pageProps = props.pageProps;
  React.useEffect(function () {
        return set_body_class(pageProps);
      });
  var router = Router.useRouter();
  var content = React.createElement(props.Component, pageProps);
  var match = router.route;
  if (match === "/examples") {
    return React.createElement(MainLayout.make, {
                children: null
              }, React.createElement("h1", {
                    className: "font-bold"
                  }, "Examples Section"), React.createElement("div", undefined, content));
  } else {
    return React.createElement(MainLayout.make, {
                children: content
              });
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
